# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Title goes here
email: email@addressgoeshere
category: TV &amp; Film # needs to be a valid category
description: > # this means to ignore newlines until "baseurl:"
  Short description of your podcast.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://customdomain.here" # the base hostname & protocol for your site
twitter_username: example
author: authornamehere
logo: logo.png
copyright: "&#x2117; &amp; &#xA9; 2020"

# Build settings
markdown: kramdown
